export const SET_LIST_USER = 'listUser/setListUser'
export const SET_USER_PER_PAGE = 'userPerPage/setUserPerPage'
export const SET_FILTER_USER = 'filterUser/setFilterUser'
export const SET_LIST_USER_LOADING = 'listUserLoading/setListUserLoading'
export const SET_LIST_USER_ERROR = 'listUserError/setListUserError'